### ISSUE TITLE
Erro Collection - houdini 18

### ISSUE THREAD

**Issue by lobaojr** [pedohorse/hpaste#19]
Good afternoon my friend.
I'm having a type of error in houdini18 which is as follows:

I cannot add nodes to my collection.
Then I have to go back to houdini 17, have him add it to my collection and then he appears on 18.

When you order your collection to be added at 18, he does not open the window to enter the name and send it.

Thank you very much .. Your plugin is fantastic.

**Comment by pedohorse** [comment]
i'm sorry for just checking notifications now.
i will check that

**Comment by pedohorse** [comment]
it should be fixed now,
update from master branch, or release 1.1.1
