### ISSUE TITLE
Stop requiring access to private gists

### ISSUE THREAD

**Issue by MaxPleaner** [pedohorse/hpaste#36]
Private gists are private. There's no reason this application should require access to them. It's sketchy, potentially a security vulnerability, etc.

**Comment by pedohorse** [comment]
hey @MaxPleaner !

The private gists access is only requested if you **choose** to add your github account to hcollections to store scene snippets as public/private gists.
The whole point of collections is to store parts of the scene you want to save in private collections, so private gist access is requested.

As far as i remember, github's scopes do not allow for more granular access to gists - it's either all, or none (like in read-only public gists). So if you **choose** to use collections to store your snippets as gists - you will have to grant the app access to them.

But you can also connect read-only accounts to your collection list, which gives you the ability to read their public snippets
